/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dosen;
import Main.MenuDosen;
import Main.MenuMahasiswa;
import config.connectdb;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author ASUS
 */
public class JadwalUjian extends javax.swing.JFrame {

    String nama_dsn, email_dsn;
    String nim_mhs, nama_mhs, email_mhs, nilai_perusahaan;
    private DefaultTableModel tableujian;
    
    public JadwalUjian() {
        setResizable(false);
        initComponents();
        dsnlogin();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        caridata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnpresent = new javax.swing.JButton();
        btnabsent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablejadwal = new javax.swing.JTable();
        btnunduh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 53));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jadwal Ujian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        jLabel7.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UMM - 2021");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridataActionPerformed(evt);
            }
        });
        caridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caridataKeyReleased(evt);
            }
        });
        jPanel2.add(caridata, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 24, 155, 30));

        jLabel3.setText("Search");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 24, 49, 30));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 372, -1, 40));

        btnpresent.setText("Present");
        btnpresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpresentActionPerformed(evt);
            }
        });
        jPanel2.add(btnpresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, 40));

        btnabsent.setText("Absent");
        btnabsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabsentActionPerformed(evt);
            }
        });
        jPanel2.add(btnabsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, 40));

        tablejadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablejadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablejadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablejadwal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 782, 267));

        btnunduh.setText("Download Laporan");
        btnunduh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunduhActionPerformed(evt);
            }
        });
        jPanel2.add(btnunduh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(818, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void TampilData(){
        
        Connection con = connectdb.tryConnect();
        
            tableujian = new DefaultTableModel();
            tableujian.addColumn("DATE");
            tableujian.addColumn("NIM");
            tableujian.addColumn("NAMA MAHASISWA");
            tablejadwal.setModel(tableujian);
        
        try {
            java.sql.Statement stat = con.createStatement();
            ResultSet res=stat.executeQuery ("select * from ujian where dsn_penguji='" +nama_dsn+"'");
            
            while(res.next()) {
                tableujian.addRow(new Object[]{
                    res.getString("date"),
                    res.getString("nim"),
                    res.getString("nama")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuDosen frm = new MenuDosen();
        frm.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caridataActionPerformed

    private void caridataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caridataKeyReleased
       String key = caridata.getText();
       
        if(key!=""){
            cari(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_caridataKeyReleased

    private void btnabsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabsentActionPerformed
        ambilData();
        Object[] options = {"Iya","Batal"};
        int n = JOptionPane.showOptionDialog(null,nama_mhs + " tidak hadir?","Perhatian!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, options, options[0]); 
        if(n == JOptionPane.YES_OPTION){
//            deleteData();
            insertArsip("Absent");
            TampilData();
        }
    }//GEN-LAST:event_btnabsentActionPerformed

    private void tablejadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablejadwalMouseClicked
        int baris = tablejadwal.getSelectedRow(); 
        
         nim_mhs=(String) tablejadwal.getValueAt(baris,1);
        nama_mhs=(String) tablejadwal.getValueAt(baris,2);
        
    }//GEN-LAST:event_tablejadwalMouseClicked

    private void btnpresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpresentActionPerformed
        ambilData();
        insertData();
//        deleteData();
        insertArsip("Present");
        TampilData();
    }//GEN-LAST:event_btnpresentActionPerformed

    private void btnunduhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunduhActionPerformed
        try {
            Connection conn = connectdb.tryConnect();
            Statement stat = conn.createStatement();
            String sql = "select uploadlaporan from ujian where nim='"+nim_mhs+"'";
            ResultSet res = stat.executeQuery(sql);
            
            String namafile = String.format("File\\Laporan\\Laporan_%s.pdf",nim_mhs);
            File file = new File(namafile);
            FileOutputStream output = new FileOutputStream(file);
            
            if(res.next()){
                InputStream input = res.getBinaryStream("uploadlaporan");
                byte[] buffer = new byte[1024];
                
                while(input.read(buffer)>0){
                    output.write(buffer);
                }
            }
            output.close();
            
            JOptionPane.showMessageDialog(null, "File Saved in " + file.getAbsoluteFile(), "pesan", JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println(file.getAbsoluteFile());
            
            
        }  catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnunduhActionPerformed

    public void cari(String key){
        Connection con = connectdb.tryConnect();
        
            tableujian = new DefaultTableModel();
            tableujian.addColumn("DATE");
            tableujian.addColumn("NIM");
            tableujian.addColumn("NAMA MAHASISWA");
        
            tablejadwal.setModel(tableujian);
        
        try {
            java.sql.Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery("SELECT * from ujian WHERE date LIKE '%"+key+"%' OR nim LIKE '%"+key+"%' OR nama LIKE '%"+key+"%'");  

            while (res.next() && res.getString("dsn_penguji").equals(nama_dsn)) {
               
                tableujian.addRow(new Object[]{
                    res.getString("date"),
                    res.getString("nim"),
                    res.getString("nama")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void insertData(){
        Connection con = connectdb.tryConnect();
        PreparedStatement ps;
        try{
               String sql = ("insert into nilai values(?,?,?,?,?,?,?,?)");
               ps  = con.prepareStatement(sql);
               
               ps.setString(1, nim_mhs); // nim nama email dsn nilai_perusahaan niilai_dsn nilai_total
               ps.setString(2, nama_mhs);
               ps.setString(3, email_mhs);
               ps.setString(4, nama_dsn); Double asd = Double.parseDouble(nilai_perusahaan);
               ps.setDouble(5, asd);
               ps.setDouble(6, 0);
               DecimalFormat formatData = new DecimalFormat("#.##");
               double total  = Double.valueOf(formatData.format(0.6 * asd));
               ps.setDouble(7, total);
               ps.setString(8,"-");
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data Inserted");
              
           }catch(Exception ex){
               JOptionPane.showMessageDialog(null, "Data not Inserted");
           }
    }
    
    public void deleteData(){
        Connection con = connectdb.tryConnect();
        try
         {
            String sql="delete from ujian where nim='"+nim_mhs+"'";
            PreparedStatement st=con.prepareStatement(sql);
            st.executeUpdate();
            
         }
        catch (Exception e)
        {
            System.out.println("Gagal");
        }
    }
    
    public void insertArsip(String status){
        try {
        Connection con = connectdb.tryConnect();
        PreparedStatement ps = con.prepareStatement("insert into arsip values(?,?,?,?)");
               ps.setString(1, nim_mhs);
               ps.setString(2, nama_mhs);
               ps.setString(3, email_mhs);
               ps.setString(4, status);
               ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        
    public void ambilData(){
        
        Connection con = connectdb.tryConnect();
        try{
        java.sql.Statement stat = con.createStatement();
            ResultSet res=stat.executeQuery ("select * from ujian where nim='" +nim_mhs+"'");
            
            while(res.next()) {
                email_mhs=(String)res.getString("email");
                nilai_perusahaan = (String)res.getString("nilai");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    
    public void dsnlogin(){
        FileReader file;
        BufferedReader buff;
        try {
            file = new FileReader("dsn.txt");
            buff = new BufferedReader(file);
        
            String data = buff.readLine();
            StringTokenizer token = new StringTokenizer(data, ",");
            nama_dsn = token.nextToken();
            email_dsn = token.nextToken();
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuDosen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuDosen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalUjian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabsent;
    private javax.swing.JButton btnpresent;
    private javax.swing.JButton btnunduh;
    private javax.swing.JTextField caridata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablejadwal;
    // End of variables declaration//GEN-END:variables
}
