/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dosen;
import Main.MenuDosen;
import Main.MenuMahasiswa;
import config.connectdb;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author ASUS
 */
public class JadwalUjian extends javax.swing.JFrame {

    String nama_dsn, email_dsn;
    String nim_mhs, nama_mhs, email_mhs, nilai_perusahaan;
    private DefaultTableModel tableujian;
    
    public JadwalUjian() {
        setResizable(false);
        initComponents();
        dsnlogin();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        caridata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablejadwal = new javax.swing.JTable();
        btnBack = new javax.swing.JLabel();
        btnDownload = new javax.swing.JLabel();
        btnAbsent = new javax.swing.JLabel();
        btnPresent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 53));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jadwal Ujian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridataActionPerformed(evt);
            }
        });
        caridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caridataKeyReleased(evt);
            }
        });

        jLabel3.setText("Search");

        tablejadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablejadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablejadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablejadwal);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Red Vol.2/arrow-92-24.png"))); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnDownload.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Red Vol.2/download-2-24.png"))); // NOI18N
        btnDownload.setText("Download Laporan");
        btnDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDownloadMouseClicked(evt);
            }
        });

        btnAbsent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAbsent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Red Vol.2/x-mark-5-24.png"))); // NOI18N
        btnAbsent.setText("Absent");
        btnAbsent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbsentMouseClicked(evt);
            }
        });

        btnPresent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPresent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Red Vol.2/check-mark-8-24.png"))); // NOI18N
        btnPresent.setText("Present");
        btnPresent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPresentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(578, 578, 578)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownload)
                        .addGap(132, 132, 132)
                        .addComponent(btnAbsent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPresent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnDownload, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAbsent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPresent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(802, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void TampilData(){
        
        Connection con = connectdb.tryConnect();
        
            tableujian = new DefaultTableModel();
            tableujian.addColumn("DATE");
            tableujian.addColumn("NIM");
            tableujian.addColumn("NAMA MAHASISWA");
            tablejadwal.setModel(tableujian);
        
        try {
            java.sql.Statement stat = con.createStatement();
            ResultSet res=stat.executeQuery ("select * from ujian where dsn_penguji='" +nama_dsn+"'");
            
            while(res.next()) {
                tableujian.addRow(new Object[]{
                    res.getString("date"),
                    res.getString("nim"),
                    res.getString("nama")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caridataActionPerformed

    private void caridataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caridataKeyReleased
       String key = caridata.getText();
       
        if(key!=""){
            cari(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_caridataKeyReleased

    private void tablejadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablejadwalMouseClicked
        int baris = tablejadwal.getSelectedRow(); 
        
         nim_mhs=(String) tablejadwal.getValueAt(baris,1);
        nama_mhs=(String) tablejadwal.getValueAt(baris,2);
        
    }//GEN-LAST:event_tablejadwalMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        MenuDosen frm = new MenuDosen();
        frm.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();       
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDownloadMouseClicked
        try {
            Connection conn = connectdb.tryConnect();
            Statement stat = conn.createStatement();
            String sql = "select uploadlaporan from ujian where nim='"+nim_mhs+"'";
            ResultSet res = stat.executeQuery(sql);
            
            String namafile = String.format("File\\Laporan\\Laporan_%s.pdf",nim_mhs);
            File file = new File(namafile);
            FileOutputStream output = new FileOutputStream(file);
            
            if(res.next()){
                InputStream input = res.getBinaryStream("uploadlaporan");
                byte[] buffer = new byte[1024];
                
                while(input.read(buffer)>0){
                    output.write(buffer);
                }
            }
            
            
            JOptionPane.showMessageDialog(null, "File Saved in " + file.getAbsoluteFile(), "pesan", JOptionPane.INFORMATION_MESSAGE);
            output.close();
            
            System.out.println(file.getAbsoluteFile());
            
            
        }  catch (Exception ex) {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_btnDownloadMouseClicked

    private void btnAbsentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbsentMouseClicked
        ambilData();
        Object[] options = {"Iya","Batal"};
        int n = JOptionPane.showOptionDialog(null,nama_mhs + " tidak hadir?","Perhatian!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, options, options[0]); 
        if(n == JOptionPane.YES_OPTION){
            deleteData();
            insertArsip("Absent");
            TampilData();
        }
    }//GEN-LAST:event_btnAbsentMouseClicked

    private void btnPresentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresentMouseClicked
        ambilData();
        insertData();
        deleteData();
        insertArsip("Present");
        TampilData();
    }//GEN-LAST:event_btnPresentMouseClicked

    public void cari(String key){
        Connection con = connectdb.tryConnect();
        
            tableujian = new DefaultTableModel();
            tableujian.addColumn("DATE");
            tableujian.addColumn("NIM");
            tableujian.addColumn("NAMA MAHASISWA");
        
            tablejadwal.setModel(tableujian);
        
        try {
            java.sql.Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery("SELECT * from ujian WHERE date LIKE '%"+key+"%' OR nim LIKE '%"+key+"%' OR nama LIKE '%"+key+"%'");  

            while (res.next() && res.getString("dsn_penguji").equals(nama_dsn)) {
               
                tableujian.addRow(new Object[]{
                    res.getString("date"),
                    res.getString("nim"),
                    res.getString("nama")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void insertData(){
        Connection con = connectdb.tryConnect();
        PreparedStatement ps;
        try{
               String sql = ("insert into nilai values(?,?,?,?,?,?,?,?)");
               ps  = con.prepareStatement(sql);
               
               ps.setString(1, nim_mhs); // nim nama email dsn nilai_perusahaan niilai_dsn nilai_total
               ps.setString(2, nama_mhs);
               ps.setString(3, email_mhs);
               ps.setString(4, nama_dsn); Double asd = Double.parseDouble(nilai_perusahaan);
               ps.setDouble(5, asd);
               ps.setDouble(6, 0);
               DecimalFormat formatData = new DecimalFormat("#.##");
               double total  = Double.valueOf(formatData.format(0.6 * asd));
               ps.setDouble(7, total);
               ps.setString(8,"-");
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data Inserted");
              
           }catch(Exception ex){
               JOptionPane.showMessageDialog(null, "Data not Inserted");
           }
    }
    
    public void deleteData(){
        Connection con = connectdb.tryConnect();
        try
         {
            String sql="update ujian set dsn_penguji='Sampun' where nim='"+nim_mhs+"'";
            PreparedStatement st=con.prepareStatement(sql);
            st.executeUpdate();
            
         }
        catch (Exception e)
        {
            System.out.println("Gagal");
        }
    }
    
    public void insertArsip(String status){
        try {
        Connection con = connectdb.tryConnect();
        PreparedStatement ps = con.prepareStatement("insert into arsip values(?,?,?,?)");
               ps.setString(1, nim_mhs);
               ps.setString(2, nama_mhs);
               ps.setString(3, email_mhs);
               ps.setString(4, status);
               ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        
    public void ambilData(){
        
        Connection con = connectdb.tryConnect();
        try{
        java.sql.Statement stat = con.createStatement();
            ResultSet res=stat.executeQuery ("select * from ujian where nim='" +nim_mhs+"'");
            
            while(res.next()) {
                email_mhs=(String)res.getString("email");
                nilai_perusahaan = (String)res.getString("nilai");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JadwalUjian.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    
    public void dsnlogin(){
        FileReader file;
        BufferedReader buff;
        try {
            file = new FileReader("dsn.txt");
            buff = new BufferedReader(file);
        
            String data = buff.readLine();
            StringTokenizer token = new StringTokenizer(data, ",");
            nama_dsn = token.nextToken();
            email_dsn = token.nextToken();
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuDosen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuDosen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalUjian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbsent;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnDownload;
    private javax.swing.JLabel btnPresent;
    private javax.swing.JTextField caridata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablejadwal;
    // End of variables declaration//GEN-END:variables
}
